In [324]:
import pandas as pd
import numpy as np
#df=pd.read_csv("C:\\web_scraping_project\\Amazon_scrapt_data")
#df=pd.read_csv(r"C:\Users\LENOVO\Downloads\Amazon_data_cleaning.ipynb")
df=pd.read_csv(r"C:\DataScience\Project\amazonscrab\amazon_laptops_scrap.csv")
df

,title,price,rating,brand,ram,ssd_storage,color,processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
542,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
543,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","73,490",2.5,Dell,8GB,512GB,Black,Intel
544,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
545,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.7,Apple,8GB,256GB,Silver,NaN
546,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","81,490",5.0,Dell,16GB,NaN,NaN,Intel

In [325]:
df.columns
df.isna().sum()

title            0
price            5
rating          61
brand            0
ram             33
ssd_storage     44
color           83
processor      176
dtype: int64

In [326]:
df.rename(columns={'Unnamed: 0': 'product'},inplace=True)
df

,title,price,rating,brand,ram,ssd_storage,color,processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
542,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
543,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","73,490",2.5,Dell,8GB,512GB,Black,Intel
544,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
545,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.7,Apple,8GB,256GB,Silver,NaN
546,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","81,490",5.0,Dell,16GB,NaN,NaN,Intel

In [327]:
df.head(2)

,title,price,rating,brand,ram,ssd_storage,color,processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon

In [328]:
df.columns = df.columns.str.title()
df

,Title,Price,Rating,Brand,Ram,Ssd_Storage,Color,Processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
542,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
543,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","73,490",2.5,Dell,8GB,512GB,Black,Intel
544,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
545,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.7,Apple,8GB,256GB,Silver,NaN
546,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","81,490",5.0,Dell,16GB,NaN,NaN,Intel

In [329]:
df['Title']

0      HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...
1      HP Omnibook 3, Snapdragon X Processor 45 Tops ...
2      Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...
3      ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...
4      Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
                             ...
542    HP Omnibook 3, Snapdragon X Processor 45 Tops ...
543    Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...
544    Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
545    Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
546    Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...
Name: Title, Length: 547, dtype: object

In [330]:
df['Title'] = df['Title'].str.strip()
df['Title']

0      HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...
1      HP Omnibook 3, Snapdragon X Processor 45 Tops ...
2      Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...
3      ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...
4      Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
                             ...
542    HP Omnibook 3, Snapdragon X Processor 45 Tops ...
543    Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...
544    Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
545    Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
546    Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...
Name: Title, Length: 547, dtype: object

In [331]:
df.head()

,Title,Price,Rating,Brand,Ram,Ssd_Storage,Color,Processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN

In [332]:
df

,Title,Price,Rating,Brand,Ram,Ssd_Storage,Color,Processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
542,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
543,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","73,490",2.5,Dell,8GB,512GB,Black,Intel
544,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
545,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.7,Apple,8GB,256GB,Silver,NaN
546,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","81,490",5.0,Dell,16GB,NaN,NaN,Intel

In [333]:
df['Title']

0      HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...
1      HP Omnibook 3, Snapdragon X Processor 45 Tops ...
2      Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...
3      ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...
4      Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
                             ...
542    HP Omnibook 3, Snapdragon X Processor 45 Tops ...
543    Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...
544    Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
545    Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...
546    Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...
Name: Title, Length: 547, dtype: object

In [334]:
df['Title']=df['Title'].isnull().sum()
df['Title']

0      0
1      0
2      0
3      0
4      0
      ..
542    0
543    0
544    0
545    0
546    0
Name: Title, Length: 547, dtype: int64

In [335]:
df['Title']=df['Title'].fillna('Unknown')
df['Title']

0      0
1      0
2      0
3      0
4      0
      ..
542    0
543    0
544    0
545    0
546    0
Name: Title, Length: 547, dtype: int64

In [336]:
df.head(2)

   Title   Price  Rating Brand   Ram Ssd_Storage   Color   Processor
0      0  75,990     3.6    HP  16GB       512GB  Silver       Intel
1      0  69,990     3.2    HP  16GB       512GB  Silver  Snapdragon

In [337]:
df.drop(columns=["Title"],inplace=True)
df

      Price  Rating   Brand   Ram Ssd_Storage   Color   Processor
0    75,990     3.6      HP  16GB       512GB  Silver       Intel
1    69,990     3.2      HP  16GB       512GB  Silver  Snapdragon
2    44,999     4.0  Lenovo   8GB       512GB  Silver         AMD
3    67,990     4.0    ASUS  16GB       512GB  Silver       Intel
4    73,990     4.8   Apple   8GB       256GB  Indigo         NaN
..      ...     ...     ...   ...         ...     ...         ...
542  69,990     3.2      HP  16GB       512GB  Silver  Snapdragon
543  73,490     2.5    Dell   8GB       512GB   Black       Intel
544  73,990     4.8   Apple   8GB       256GB  Indigo         NaN
545  73,990     4.7   Apple   8GB       256GB  Silver         NaN
546  81,490     5.0    Dell  16GB         NaN     NaN       Intel

[547 rows x 7 columns]

In [338]:
# clean price columns
df['Price'].info

<bound method Series.info of 0      75,990
1      69,990
2      44,999
3      67,990
4      73,990
        ...
542    69,990
543    73,490
544    73,990
545    73,990
546    81,490
Name: Price, Length: 547, dtype: object>

In [339]:
df['Price'] = df['Price'].str.replace(",", "", regex=False)
df['Price']

0      75990
1      69990
2      44999
3      67990
4      73990
       ...
542    69990
543    73490
544    73990
545    73990
546    81490
Name: Price, Length: 547, dtype: object

In [340]:
# check measing value
df['Price']=df['Price'].replace("NaN",np.nan)
df['Price']

df['Price'].isnull().sum()

np.int64(5)

In [341]:
#
df['Price'].fillna('Unkonwn')

0      75990
1      69990
2      44999
3      67990
4      73990
       ...
542    69990
543    73490
544    73990
545    73990
546    81490
Name: Price, Length: 547, dtype: object

In [342]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Price']

0      75990.0
1      69990.0
2      44999.0
3      67990.0
4      73990.0
        ...
542    69990.0
543    73490.0
544    73990.0
545    73990.0
546    81490.0
Name: Price, Length: 547, dtype: float64

In [343]:
df['Price'].duplicated().sum()

np.int64(331)

In [344]:
df['Price'].sample(45)

532    194990.0
114     69990.0
213     78990.0
437    342490.0
58      42999.0
476    342490.0
47      69990.0
242     54891.0
354    134990.0
447     69990.0
236     83490.0
410     79932.0
451     40999.0
324     79990.0
386     63990.0
265    175000.0
484     75990.0
39      32990.0
91      49990.0
45      58990.0
276     44680.0
144     41890.0
348     69990.0
462    194990.0
335     86990.0
463     65999.0
503     75990.0
376     83490.0
160     73990.0
199    194990.0
145     54650.0
55      37400.0
426    200490.0
102     54990.0
237    464490.0
67      39890.0
163     63990.0
176    290000.0
150     85000.0
483    200490.0
304     63425.0
367    342490.0
329     83490.0
8       84990.0
524    475490.0
Name: Price, dtype: float64

In [345]:
df["Price"].isna().sum()

np.int64(5)

In [346]:
df=df.dropna(subset=["Price"])

In [347]:
df["Price"].isna().sum()

np.int64(0)

In [348]:

#df['Price']=df['Price'].fillna(df['Price'].mean())
#df['Price']

In [349]:
#df['Price']=df['Price'].astype(int)
df["Price"]=pd.to_numeric(df["Price"],errors="coerce")
df['Price']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\740997073.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"]=pd.to_numeric(df["Price"],errors="coerce")

0      75990.0
1      69990.0
2      44999.0
3      67990.0
4      73990.0
        ...
542    69990.0
543    73490.0
544    73990.0
545    73990.0
546    81490.0
Name: Price, Length: 542, dtype: float64

In [350]:
df['Price'].isna().sum()

np.int64(0)

In [351]:
df.head(5)

     Price  Rating   Brand   Ram Ssd_Storage   Color   Processor
0  75990.0     3.6      HP  16GB       512GB  Silver       Intel
1  69990.0     3.2      HP  16GB       512GB  Silver  Snapdragon
2  44999.0     4.0  Lenovo   8GB       512GB  Silver         AMD
3  67990.0     4.0    ASUS  16GB       512GB  Silver       Intel
4  73990.0     4.8   Apple   8GB       256GB  Indigo         NaN

In [352]:
# clean the rating columns
df['Rating'].unique()

array([3.6, 3.2, 4. , 4.8, 4.7, 4.1, 3.8, 3.9, 4.2, 3.4, 1. , nan, 2.8,
       5. , 4.6, 3.7, 4.4, 4.3, 3.3, 3. , 3.5, 4.5, 1.6, 2.9, 2.4, 2. ,
       3.1, 2.5, 2.7, 4.9])

In [353]:
df['Rating'].isna().sum()

np.int64(61)

In [388]:
#df['Rating']=df['Rating'].fillna(df['Rating'].mean())
df=df.dropna(subset=["Rating"])
df['Rating']

0      3.6
1      3.2
2      4.0
3      4.0
4      4.8
      ...
542    3.2
543    2.5
544    4.8
545    4.7
546    5.0
Name: Rating, Length: 479, dtype: float64

In [389]:
df['Rating'].isna().sum()

np.int64(0)

In [356]:
# clean Brand columns

df['Brand'].unique()

array(['HP', 'Lenovo', 'ASUS', 'Apple', 'Dell', 'Acer', 'acer', 'MaxBook',
       'Unknown', 'Primebook', 'Alienware', 'Tech', 'MSI', 'NEW', 'DELL',
       'Samsung', 'Microsoft', 'Model', 'JioBook'], dtype=object)

In [357]:
df['Brand']=df['Brand'].replace({
    'Dell':'DELL',
    'acer':'Acer',
    
})
df['Brand']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\2548493630.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Brand']=df['Brand'].replace({

0          HP
1          HP
2      Lenovo
3        ASUS
4       Apple
        ...
542        HP
543      DELL
544     Apple
545     Apple
546      DELL
Name: Brand, Length: 542, dtype: object

In [358]:


df['Brand'].unique()

array(['HP', 'Lenovo', 'ASUS', 'Apple', 'DELL', 'Acer', 'MaxBook',
       'Unknown', 'Primebook', 'Alienware', 'Tech', 'MSI', 'NEW',
       'Samsung', 'Microsoft', 'Model', 'JioBook'], dtype=object)

In [359]:
df.drop(df[df['Brand'].isin(['Unknown', 'NEW', 'Model'])].index,inplace=True,)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\2594501963.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df[df['Brand'].isin(['Unknown', 'NEW', 'Model'])].index,inplace=True,)

In [360]:
df['Brand'].unique()

array(['HP', 'Lenovo', 'ASUS', 'Apple', 'DELL', 'Acer', 'MaxBook',
       'Primebook', 'Alienware', 'Tech', 'MSI', 'Samsung', 'Microsoft',
       'JioBook'], dtype=object)

In [361]:
df.head(5)

     Price  Rating   Brand   Ram Ssd_Storage   Color   Processor
0  75990.0     3.6      HP  16GB       512GB  Silver       Intel
1  69990.0     3.2      HP  16GB       512GB  Silver  Snapdragon
2  44999.0     4.0  Lenovo   8GB       512GB  Silver         AMD
3  67990.0     4.0    ASUS  16GB       512GB  Silver       Intel
4  73990.0     4.8   Apple   8GB       256GB  Indigo         NaN

In [362]:
## clean ram columns

df['Ram'].unique()

array(['16GB', '8GB', 'RAM', 'LPDDR4', '4GB', 'DDR5', '12GB', '24GB', nan,
       '6GB', 'LPDDR5', '32GB', 'DDR5 ', '128GB', 'DDR7', '36GB', '48GB',
       '64GB'], dtype=object)

In [363]:
df['Ram'].value_counts(dropna=False)

Ram
16GB      206
8GB       140
24GB       74
NaN        33
RAM        14
32GB       14
4GB        12
DDR5       10
6GB         9
36GB        5
48GB        3
12GB        2
LPDDR5      2
DDR7        2
64GB        2
LPDDR4      1
DDR5        1
128GB       1
Name: count, dtype: int64

In [364]:
df['Ram']=df['Ram'].str.extract(r'(\d+)').astype(float)
df['Ram']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\4058670844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ram']=df['Ram'].str.extract(r'(\d+)').astype(float)

0      16.0
1      16.0
2       8.0
3      16.0
4       8.0
       ...
542    16.0
543     8.0
544     8.0
545     8.0
546    16.0
Name: Ram, Length: 531, dtype: float64

In [365]:
df['Ram'].isnull().sum()

np.int64(47)

In [366]:
df['Ram']=df['Ram'].fillna(df['Ram'].mean())
df['Ram']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\3118508517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ram']=df['Ram'].fillna(df['Ram'].mean())

0      16.0
1      16.0
2       8.0
3      16.0
4       8.0
       ...
542    16.0
543     8.0
544     8.0
545     8.0
546    16.0
Name: Ram, Length: 531, dtype: float64

In [367]:
df['Ram']=df['Ram'].astype(int)
df['Ram']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\1745235881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ram']=df['Ram'].astype(int)

0      16
1      16
2       8
3      16
4       8
       ..
542    16
543     8
544     8
545     8
546    16
Name: Ram, Length: 531, dtype: int64

In [368]:
df.rename(columns={'Ram': 'Ram(GB)'},inplace=True)
df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\1057868821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Ram': 'Ram(GB)'},inplace=True)

       Price  Rating   Brand  Ram(GB) Ssd_Storage   Color   Processor
0    75990.0     3.6      HP       16       512GB  Silver       Intel
1    69990.0     3.2      HP       16       512GB  Silver  Snapdragon
2    44999.0     4.0  Lenovo        8       512GB  Silver         AMD
3    67990.0     4.0    ASUS       16       512GB  Silver       Intel
4    73990.0     4.8   Apple        8       256GB  Indigo         NaN
..       ...     ...     ...      ...         ...     ...         ...
542  69990.0     3.2      HP       16       512GB  Silver  Snapdragon
543  73490.0     2.5    DELL        8       512GB   Black       Intel
544  73990.0     4.8   Apple        8       256GB  Indigo         NaN
545  73990.0     4.7   Apple        8       256GB  Silver         NaN
546  81490.0     5.0    DELL       16         NaN     NaN       Intel

[531 rows x 7 columns]

In [369]:
## clean Ssd_Storage

df['Ssd_Storage'].unique()

array(['512GB', '256GB', '1TB', nan, '2TB', '64GB', '128GB', '500GB'],
      dtype=object)

In [370]:
df['Ssd_Storage'].isnull().sum()

np.int64(44)

In [371]:
def convert_storage(x):
    if pd.isna(x):
        return x
    if "TB" in x:
        return float(x.replace("TB", "")) * 1024
    return float(x.replace("GB", ""))

df["Ssd_Storage"] = df["Ssd_Storage"].apply(convert_storage)
df["Ssd_Storage"]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\1538568895.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ssd_Storage"] = df["Ssd_Storage"].apply(convert_storage)

0      512.0
1      512.0
2      512.0
3      512.0
4      256.0
       ...
542    512.0
543    512.0
544    256.0
545    256.0
546      NaN
Name: Ssd_Storage, Length: 531, dtype: float64

In [372]:
df["Ssd_Storage"] = df["Ssd_Storage"].fillna(df["Ssd_Storage"].mean())
df["Ssd_Storage"]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\1445227655.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ssd_Storage"] = df["Ssd_Storage"].fillna(df["Ssd_Storage"].mean())

0      512.000000
1      512.000000
2      512.000000
3      512.000000
4      256.000000
          ...
542    512.000000
543    512.000000
544    256.000000
545    256.000000
546    721.453799
Name: Ssd_Storage, Length: 531, dtype: float64

In [373]:
df["Ssd_Storage"] = df["Ssd_Storage"].astype(int)
df["Ssd_Storage"]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\2371606479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ssd_Storage"] = df["Ssd_Storage"].astype(int)

0      512
1      512
2      512
3      512
4      256
      ...
542    512
543    512
544    256
545    256
546    721
Name: Ssd_Storage, Length: 531, dtype: int64

In [374]:
df['Ssd_Storage'].isnull().sum()

np.int64(0)

In [375]:
df.rename(columns={'Ssd_Storage': 'Ssd_Storage(GB)'},inplace=True)
df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\3088064396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Ssd_Storage': 'Ssd_Storage(GB)'},inplace=True)

       Price  Rating   Brand  Ram(GB)  Ssd_Storage(GB)   Color   Processor
0    75990.0     3.6      HP       16              512  Silver       Intel
1    69990.0     3.2      HP       16              512  Silver  Snapdragon
2    44999.0     4.0  Lenovo        8              512  Silver         AMD
3    67990.0     4.0    ASUS       16              512  Silver       Intel
4    73990.0     4.8   Apple        8              256  Indigo         NaN
..       ...     ...     ...      ...              ...     ...         ...
542  69990.0     3.2      HP       16              512  Silver  Snapdragon
543  73490.0     2.5    DELL        8              512   Black       Intel
544  73990.0     4.8   Apple        8              256  Indigo         NaN
545  73990.0     4.7   Apple        8              256  Silver         NaN
546  81490.0     5.0    DELL       16              721     NaN       Intel

[531 rows x 7 columns]

In [376]:
df['Ssd_Storage(GB)'].unique()

array([ 512,  256, 1024,  721, 2048,   64,  128,  500])

In [377]:
## clean Color

df['Color'].unique()

array(['Silver', 'Indigo', 'Blue', 'Grey', 'Gray', 'Black', nan, 'gray',
       'White'], dtype=object)

In [378]:
df['Color']=df['Color'].str.title()
df['Color']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\1859432411.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Color']=df['Color'].str.title()

0      Silver
1      Silver
2      Silver
3      Silver
4      Indigo
        ...
542    Silver
543     Black
544    Indigo
545    Silver
546       NaN
Name: Color, Length: 531, dtype: object

In [379]:
df['Color'].isna().sum()

np.int64(72)

In [380]:
df['Color']=df['Color'].fillna('sky-blue')
df['Color']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\954410774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Color']=df['Color'].fillna('sky-blue')

0        Silver
1        Silver
2        Silver
3        Silver
4        Indigo
         ...
542      Silver
543       Black
544      Indigo
545      Silver
546    sky-blue
Name: Color, Length: 531, dtype: object

In [381]:
df['Color'].unique()

array(['Silver', 'Indigo', 'Blue', 'Grey', 'Gray', 'Black', 'sky-blue',
       'White'], dtype=object)

In [382]:
df['Color'].isna().sum()

np.int64(0)

In [383]:
# clean Processor cloumns

df['Processor'].unique()

array(['Intel', 'Snapdragon', 'AMD', nan, 'MediaTek'], dtype=object)

In [384]:
df['Processor'].isna().sum()

np.int64(167)

In [385]:
df['Processor']=df['Processor'].fillna('Intel')
df['Processor']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1648\3871453677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Processor']=df['Processor'].fillna('Intel')

0           Intel
1      Snapdragon
2             AMD
3           Intel
4           Intel
          ...
542    Snapdragon
543         Intel
544         Intel
545         Intel
546         Intel
Name: Processor, Length: 531, dtype: object

In [390]:
df.to_csv('Amazon_clear_Data.csv', index=False)