In [1]:
## 1. Remove leading/trailing spaces from column names
Explanation: Column names like "Booking ID " and "Customer Name" have extra spaces. This
causes errors when you try to select columns. Just strip the spaces so names become clean
(Booking ID, Customer Name).

SyntaxError: invalid syntax (4038257228.py, line 2)

In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Hotel_booking_dataset.csv")
df.head(5)
df.columns

Index([' Booking ID ', 'Customer Name', ' Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

In [2]:
df.columns = df.columns.str.strip()
df.columns

Index(['Booking ID', 'Customer Name', 'Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

In [3]:
df['Booking ID']=df['Booking ID'].str.strip()
df['Booking ID']

0       BKG01888
1       BKG00789
2       BKG00757
3       BKG01079
4       BKG00218
          ...
2020    BKG01738
2021    BKG01193
2022    BKG01210
2023    BKG01060
2024    BKG00642
Name: Booking ID, Length: 2025, dtype: object

In [4]:
df.columns

Index(['Booking ID', 'Customer Name', 'Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

# 2. Standardize all date formats into one consistent format (YYYY-MM-DD)
Explanation: Dates appear as 2025-05-17 00:00:00, 2025/02/20, 15/01/2025, and even
invalid ones like 32/13/2025. Convert everything to a single clean format and turn bad dates
into missing values.

In [5]:
df['Booking Date']=pd.to_datetime(df['Booking Date'],errors="coerce").dt.strftime('%Y-%m-%d')
df['Booking Date']

0       2025-05-17
1       2025-07-29
2       2025-10-19
3       2025-12-14
4       2025-01-20
           ...
2020    2025-11-27
2021    2025-10-22
2022    2025-07-11
2023    2025-01-24
2024    2025-04-06
Name: Booking Date, Length: 2025, dtype: object

In [6]:
df['Booking Date'].isnull().sum()

np.int64(30)

In [7]:
## 3. Handle completely missing Customer Name values
Explanation: Some rows have blank Customer Name or values like N/A. Decide whether to
fill them with a placeholder (e.g., “Unknown”) or drop those rows, depending on whether
the name is critical for analysis.

SyntaxError: invalid character '“' (U+201C) (311312710.py, line 3)

In [ ]:
df['Customer Name'].isnull().sum()

In [ ]:
df['Customer Name'] = df['Customer Name'].replace('N/A', 'Unknown')
df['Customer Name'] = df['Customer Name'].fillna('Unknown')
df['Customer Name']

In [ ]:
## 4. Fix inconsistent Gender values
Explanation: Gender appears as Male, FEMALE, male, F, M, Other, etc. Convert everything to
a standard set such as Male, Female, Other.

In [ ]:
df.head(2)

In [ ]:
df['Gender'].unique()

In [ ]:
df['Gender'].str.lower()

In [ ]:
df['Gender'].unique()

In [ ]:
df['Gender'] = df['Gender'].replace({
    'male': 'Male',
    'female': 'Female',
    'M': 'Male',
    'F': 'Female',
    'Other': 'Unknown',
    'FEMALE':'Female',
    'female': 'Female',
})
df['Gender']

In [ ]:
df['Gender'].unique()

In [ ]:
## 5. Clean and standardize City names
Explanation: Cities have typos and casing issues (mumbai, Mumbai , Bangalore, Hydrabad,
blank). Correct spelling, remove extra spaces, and make casing consistent (e.g., Title Case).

In [ ]:
df['City'].unique()

In [ ]:
df['City'].str.title()

In [ ]:
df['City'].unique()

In [ ]:
df['City']=df['City'].replace({
    'mumbai':'Mumbai',
    'Bangalore':'Bengaluru',
    'Hydrabad':'Hyderabad',
    'nan':'unknown',
})
print(df['City'])

In [ ]:
## 6. Standardize Room Type categories
Explanation: Room Type has Suite, Deluxe, delux, standard, exec, Unknown, and blanks.
Map similar values to a clean list: Standard, Deluxe, Suite, Executive.

In [ ]:
df['Room Type'].unique()

In [ ]:
df['Room Type'].str.title()

In [ ]:
df['Room Type'] = df['Room Type'].str.strip().replace({
    'standard': 'Standard',
    'Standard': 'Standard',
    'delux': 'Deluxe',
    'Deluxe': 'Deluxe',
    'Suite': 'Suite',
    'exec': 'Executive',
    'Unknown': 'Unknown',
    '': 'Unknown'
})
df['Room Type']

In [ ]:
## 7. Clean Booking Channel values
Explanation: Values include Online, online, Walk-in, Travel Agent, TravelAgent, corp,
Corporate. Unify them into a small consistent set (Online, Walk-in, Corporate, Travel Agent).

In [ ]:
df['Booking Channel'].unique()

In [ ]:
df['Booking Channel'].str.title().str.strip()

In [ ]:
df['Booking Channel']=df['Booking Channel'].replace({
    'Online': 'Online',
    'online': 'Online',
    'Walk-in': 'Walk-in',
    'Travel Agent': 'Travel Agent',
    'TravelAgent': 'Travel Agent',
    'corp': 'Corporate',
    'Corporate': 'Corporate'
})
df['Booking Channel']

In [ ]:
## 8. Standardize Customer Segment
Explanation: Segments appear as Premium, regular, REG, Budget , VIP, etc. Create a clean set
such as Budget, Regular, Premium, Corporate, VIP and map everything to it.

In [ ]:
df.head(1)

In [ ]:
df['Customer Segment'].str.title()

In [ ]:
df['Customer Segment'].unique()

In [ ]:
df['Customer Segment']=df['Customer Segment'].replace({
    'Premium':'Premium',
    'Corporate':'Corporate',
    'premium':'Premium',
    'Regular':'Regular',
    'regular':'Regular',
    'budget':'Budget',
    'VIP':'VIP',
    'REG':'Regular',
})
df['Customer Segment']

In [ ]:
## 9. Fix Age column (invalid and non-numeric values)
Explanation: Age has numbers, blanks, 30 yrs, 25 years, 45Y, and impossible values like 150
or 100. Extract the number, convert to integer, and set unrealistic ages (e.g., <18 or >100) to
missing.

In [ ]:
df.head(2)

In [ ]:
df['Age'] = df['Age'].astype(str).str.extract(r'(\d+)')[0]
df['Age']

In [ ]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age']

In [ ]:
print(df['Age'].head(20).tolist())

In [ ]:
print(df['Age'].dtype)

In [ ]:
df.head(2)

In [ ]:
## 10. Clean Room Nights column
Explanation: Values include numbers, N/A, 3 nights, 100, 30. Extract only the numeric part,
convert to integer, and decide what to do with extreme values (e.g., 100 nights).

In [ ]:
df['Room Nights'].unique()

In [ ]:
df['Room Nights'].replace({
    '3 night':3,
    'two':2,
    '5 days':5,
})

In [ ]:
df['Room Nights']=pd.to_numeric(df['Room Nights'],errors='coerce')
df['Room Nights'] = df['Room Nights'].fillna(0).astype(int)
df['Room Nights']

In [ ]:
df['Room Nights'].dtype

In [ ]:
df['Room Nights'].unique()

In [ ]:
df['Room Nights'].replace('100','unknown')

In [ ]:
df['Room Nights'].unique()

In [ ]:
## 11. Fix Room Rate (mixed formats and extreme values)
Explanation: Room Rate contains normal numbers, 15k, $8000, 12000 INR, 100000, 250000,
and blanks. Convert text formats to numbers, remove currency symbols, and flag or handle
unrealistic rates.

In [ ]:
df.columns

In [ ]:
df['Room Rate']=pd.to_numeric(df['Room Rate'],errors='coerce')
df['Room Rate']=df['Room Rate'].fillna(0).astype(int)
df['Room Rate']

In [ ]:
df['Room Rate']=df['Room Rate'].replace({
    '15k':'15000',
    '$8000':'8000',
    'INR':'',
    
    
})
df['Room Rate']

In [ ]:
df.loc[(df['Room Rate']<0) | (df['Room Rate']>1000000),'Room Rate']=pd.NA

In [ ]:
df['Room Rate']

In [ ]:
## 12. Clean Discount % column
Explanation: Discount has numbers, none, 10%, 5 %, N/A, and impossible values like 120.
Convert everything to a pure number between 0 and 100; treat “none” as 0 and values >100
as missing or capped.

In [ ]:
df.columns

In [ ]:
df['Discount %'] = (
    df['Discount %']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.strip()
)

df['Discount %'] = pd.to_numeric(
    df['Discount %'],
    errors='coerce'
)



df['Discount %']=df['Discount %'].fillna(0).astype(int)
df['Discount %']

In [ ]:
df.loc[(df['Discount %']<0) | (df['Discount %']>100),'Discount %']=pd.NA

In [ ]:
df['Discount %']

In [ ]:
##13. Handle missing and invalid Rating values
Explanation: Rating has numbers, blanks, 5/5, 4 stars, and values above 5 (e.g., 6, 9).
Convert to a 1–5 scale and set invalid entries to missing.

In [ ]:
df.columns

In [ ]:
df['Rating'].unique()

In [ ]:
df['Rating']=df['Rating'].fillna(0)
df['Rating']

In [ ]:
df['Rating'].unique()

In [ ]:
df['Rating'] = df['Rating'].replace({
    '4 stars': '4',
    '5/5': '5',
    'good':pd.NA,
})
df['Rating']

In [ ]:
df['Rating']=pd.to_numeric(df['Rating'],errors='coerce')
df['Rating']

In [ ]:
df.loc[(df['Rating'] <1) | (df['Rating']>5),'Rating']=pd.NA

In [ ]:
df['Rating']

In [ ]:
# 14. Clean Guests column (extreme values)
Explanation: Most values are reasonable (1–6), but some are 15, 25, or 40. Decide a sensible
maximum (e.g., 10) and set higher values to missing or investigate them.

In [ ]:
df['Guests'].unique()

In [ ]:
df.loc[(df['Guests']<1) | (df['Guests']>10),'Guests']=pd.NA

In [ ]:
df['Guests'].isnull().sum()

In [ ]:
df['Guests']=df['Guests'].fillna('unknoun')
df['Guests']

In [ ]:
## 15. Standardize Is Member column
Explanation: Values are mixed: 1, 0, Y, Yes, Member, blanks. Convert everything to a clear
Yes/No or 1/0 format.

In [ ]:
df['Is Member']=df['Is Member'].replace({
    '1':'Yes',
    '0':'No',
    'Y':'Yes',
    'Member':pd.NA,
    'blanks':pd.NA,
    'N':'No'
})
df['Is Member']

In [ ]:
df['Is Member'].unique()

In [ ]:
## 16. Standardize Cancelled column
Explanation: Cancelled appears as 0, 1, Yes, Y, N. Convert to a consistent 0/1 or Yes/No
format.

In [ ]:
df.columns

In [ ]:
df['Cancelled'].unique()

In [ ]:
df['Cancelled']=df['Cancelled'].replace({
    '0':'No',
    '1':'Yes',
    'Y':'Yes',
    'Not Cancelled':pd.NA,
    'Cancelled':pd.NA,
    'N':'No',
    'Yes':'Yes',
    'No':'No',
})
df['Cancelled']

In [ ]:
df['Cancelled'].unique()

In [ ]:
## 17. Clean Payment Method values
Explanation: Payment methods have inconsistent casing and spacing (Credit Card, credit
card, upi, Net Banking, cash , blanks). Standardize to a clean list (Credit Card, Debit Card, UPI,
Net Banking, Cash).

In [ ]:
df['Payment Method'].unique()

In [ ]:
df['Payment Method'].str.title()

In [ ]:
df['Payment Method']=df['Payment Method'].replace({
    'upi':'UPI',
    'netbanking':'Net Banking',
    ' ':'',
    'cash ':'Cash',
    'CreditCard':'Credit Card',
    
})
df['Payment Method']

In [ ]:
df['Payment Method'].unique()

In [ ]:
## 18. Remove or flag duplicate Booking IDs
Explanation: Some Booking IDs (e.g., BKG00042, BKG01640) appear more than once. Decide
whether to keep the first occurrence, the most complete row, or mark them for review.

In [ ]:
df.columns

In [ ]:
df.drop_duplicates(subset="Booking ID", keep=False)
df['Booking ID']

In [ ]:
df['Booking ID'].duplicated(keep=False)

In [ ]:
df

In [ ]:
## 19. Handle missing Room Type values
Explanation: Some rows have blank Room Type. You can either drop those rows, fill with
“Unknown”, or try to infer from other columns if possible.

In [ ]:
df.columns

In [ ]:
df['Room Type'].isnull().sum()

In [ ]:
df['Room Type'].fillna('unknown')

In [26]:
df['Room Type'].unique()

array(['Suite', 'Deluxe', 'Standard', 'Executive', nan, 'standard',
       'STANDARD', 'delux', 'exec', 'Unknown', 'suite', 'Deluxe ',
       'Executive '], dtype=object)

In [9]:
## 20. Fix inconsistent Final Amount calculations
Explanation: Final Amount should roughly equal Gross Amount − Discount Amount, but
some rows have missing Final Amount or clear calculation errors. Recalculate or flag
inconsistencies.

SyntaxError: invalid character '−' (U+2212) (1332910945.py, line 2)

In [25]:
df['Final Amount']

0       29577.629424
1        4086.975525
2       50759.174704
3       13927.806936
4        10524.88998
            ...
2020     12573.33552
2021     33723.66677
2022     56438.28432
2023     12130.83564
2024     6619.502435
Name: Final Amount, Length: 2025, dtype: object

In [ ]:
## 21. Clean Customer Name (placeholder and invalid names)
Explanation: Names include Customer_1888, 12345, john doe, N/A, blanks. Decide how to
treat non-real names (keep as-is, replace with “Unknown”, or drop).

In [24]:
df["Customer Name"] = df["Customer Name"].replace({
    '["N/A", "NA", "n/a", "null", "None", ""]',"Unknown",
})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_25424\1109031513.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df["Customer Name"] = df["Customer Name"].replace({

In [23]:
df['Customer Name'].unique()

array(['Customer_1888', 'Customer_0789', 'Customer_0757', ...,
       'Customer_1210', 'Customer_1060', 'Customer_0642'],
      shape=(1951,), dtype=object)

In [ ]:
## 22. Convert all numeric columns to proper numeric data types
Explanation: Many columns that should be numbers are currently stored as text because of
mixed formats. Convert them to integer or float so calculations work correctly.

In [21]:
df.dtypes

Booking ID                  object
Customer Name               object
Booking Date        datetime64[ns]
City                        object
Room Type                   object
Booking Channel             object
Customer Segment            object
Gender                      object
Age                         object
Room Nights                float64
Room Rate                   object
Discount %                  object
Rating                      object
Guests                       int64
Is Member                   object
Cancelled                   object
Payment Method              object
Gross Amount               float64
Discount Amount            float64
Final Amount                object
Hotel Cost                 float64
Profit                     float64
dtype: object

In [20]:
df['Room Nights']=pd.to_numeric(df['Room Nights'],errors='coerce')
df['Room Nights']

0       4.0
1       1.0
2       4.0
3       3.0
4       NaN
       ...
2020    3.0
2021    5.0
2022    6.0
2023    2.0
2024    5.0
Name: Room Nights, Length: 2025, dtype: float64

In [19]:
df['Room Nights'].unique()

array(['4', '1', '3', nan, '2', '5', '100', '7', '6', '30', '3 nights',
       'two', '5 days', '50'], dtype=object)

In [ ]:
## 23. Handle missing values in key financial columns (Gross Amount, Discount Amount, Final
Amount, Profit)
Explanation: Some financial columns have blanks. Decide whether to drop those rows, fill
with 0, or calculate missing values from other columns when possible.

In [18]:
df[['Gross Amount','Discount Amount','Final Amount','Profit']].isnull().sum()

Gross Amount       0
Discount Amount    0
Final Amount       0
Profit             0
dtype: int64

In [10]:
df[['Gross Amount','Discount Amount','Final Amount','Profit']]=df[['Gross Amount','Discount Amount','Final Amount','Profit']].fillna('unknown')
df[['Gross Amount','Discount Amount','Final Amount','Profit']]

      Gross Amount  Discount Amount  Final Amount        Profit
0         31674.48      2096.850576  29577.629424  12676.243171
1          4822.39       735.414475   4086.975525   1340.071362
2         66334.52     15575.345296  50759.174704  10546.517239
3         19255.92      5328.113064  13927.806936   4288.745172
4         15685.38      5160.490020   10524.88998   3979.308676
...            ...              ...           ...           ...
2020      12777.78       204.444480   12573.33552   3295.541467
2021      51298.55     17574.883230   33723.66677  11415.688437
2022      79546.56     23108.275680   56438.28432  19894.152597
2023      18041.10      5910.264360   12130.83564   2447.417682
2024       7644.65      1025.147565   6619.502435   3190.744055

[2025 rows x 4 columns]

In [11]:
## 24. Remove rows with completely invalid dates
Explanation: Dates like 32/13/2025 are impossible. Identify and either remove those rows or
set the date to missing.

SyntaxError: invalid syntax (2415600840.py, line 2)

In [17]:
df["Booking Date"] = pd.to_datetime(df["Booking Date"],errors="coerce")

df["Booking Date"]

0      2025-05-17
1      2025-07-29
2      2025-10-19
3      2025-12-14
4      2025-01-20
          ...
2020   2025-11-27
2021   2025-10-22
2022   2025-07-11
2023   2025-01-24
2024   2025-04-06
Name: Booking Date, Length: 2025, dtype: datetime64[ns]

In [ ]:
## 25. Standardise boolean-like columns (Is Member and Cancelled) to the same format
Explanation: Keeping both columns in the same style (both 0/1 or both Yes/No) makes
filtering and analysis much easier and less error-prone.

In [29]:
df.columns

Index(['Booking ID', 'Customer Name', 'Booking Date', 'City', 'Room Type',
       'Booking Channel', 'Customer Segment', 'Gender', 'Age', 'Room Nights',
       'Room Rate', 'Discount %', 'Rating', 'Guests', 'Is Member', 'Cancelled',
       'Payment Method', 'Gross Amount', 'Discount Amount', 'Final Amount',
       'Hotel Cost', 'Profit'],
      dtype='object')

In [30]:
print(df['Is Member'].unique())
print(df['Cancelled'].unique())

['1' '0' 'Y' 'Yes' 'N' 'Non-Member' 'No' 'Member']
['0' '1' 'Yes' 'Y' 'Not Cancelled' 'No' 'N' 'Cancelled']

In [32]:
df['Is Member'] = df['Is Member'].replace({
    'Yes': 1,
    'No': 0,
    True: 1,
    False: 0
})

df['Cancelled'] = df['Cancelled'].replace({
    'Yes': 1,
    'No': 0,
    True: 1,
    False: 0
})
df['Cancelled']

0       0
1       0
2       1
3       0
4       0
       ..
2020    0
2021    1
2022    0
2023    1
2024    1
Name: Cancelled, Length: 2025, dtype: object

In [33]:
df['Is Member']

0       1
1       1
2       0
3       0
4       1
       ..
2020    1
2021    1
2022    1
2023    1
2024    1
Name: Is Member, Length: 2025, dtype: object

In [12]:
## 26. Trim extra spaces from all text columns
Explanation: Many text fields have leading/trailing spaces (e.g., "Budget ", "Mumbai ").
Removing them prevents “Budget” and “Budget ” from being treated as different categories.

SyntaxError: invalid character '“' (U+201C) (1095280958.py, line 3)

In [35]:
text_cols = df.select_dtypes(include="object").columns
df[text_cols] = df[text_cols].apply(lambda col: col.str.strip())
df[text_cols]

,Booking ID,Customer Name,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Rate,Discount %,Rating,Is Member,Cancelled,Payment Method,Final Amount
0,BKG01888,Customer_1888,Mumbai,Suite,Online,Premium,Male,39,7918.62,6.62,1.4,1,0,Credit Card,NaN
1,BKG00789,Customer_0789,Bengaluru,Suite,Walk-in,Corporate,Male,25,4822.39,15.25,2.5,1,0,Credit Card,NaN
2,BKG00757,Customer_0757,Pune,Suite,Corporate,Corporate,Other,50,16583.63,23.48,1.2,0,1,Credit Card,NaN
3,BKG01079,Customer_1079,Mumbai,Deluxe,Walk-in,Regular,Male,53,6418.64,27.67,2.6,0,0,Debit Card,NaN
4,BKG00218,Customer_0218,Delhi,Suite,Travel Agent,Budget,Male,38,5228.46,32.9,4.2,1,0,Cash,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,Hyderabad,Deluxe,Online,Premium,Other,52,4259.26,1.6,4.0,1,0,Net Banking,NaN
2021,BKG01193,Customer_1193,Hyderabad,Deluxe,Online,Premium,Male,33,15k,34.26,4.7,1,1,Net Banking,NaN
2022,BKG01210,Customer_1210,Mumbai,Deluxe,Online,Premium,Male,48,13257.76,29.05,1.3,1,0,Debit Card,NaN
2023,BKG01060,Customer_1060,Hyderabad,Executive,Travel Agent,Budget,Female,52,9020.55,32.76,3.8,1,1,Debit Card,NaN
2024,BKG00642,Customer_0642,Mumbai,Suite,Walk-in,Premium,Male,23,1528.93,13.41,4.8,1,1,Debit Card,NaN

In [37]:
df['Room Rate'] = (
    df['Room Rate']
    .astype(str)
    .str.replace('k', '000', case=False, regex=False)
)

df['Room Rate'] = pd.to_numeric(df['Room Rate'], errors='coerce')
df['Room Rate']

0        7918.62
1        4822.39
2       16583.63
3        6418.64
4        5228.46
          ...
2020     4259.26
2021    15000.00
2022    13257.76
2023     9020.55
2024     1528.93
Name: Room Rate, Length: 2025, dtype: float64

In [39]:
df['Discount %'] = pd.to_numeric(df['Discount %'], errors='coerce')
df['Final Amount'] = df['Room Rate'] * (1 - df['Discount %'] / 100)
df['Final Amount']

0        7394.407356
1        4086.975525
2       12689.793676
3        4642.602312
4        3508.296660
            ...
2020     4191.111840
2021     9861.000000
2022     9406.380720
2023     6065.417820
2024     1323.900487
Name: Final Amount, Length: 2025, dtype: float64

In [40]:
df

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17,Mumbai,Suite,Online,Premium,Male,39,4.0,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,7394.407356,16901.386253,12676.243171
1,BKG00789,Customer_0789,2025-07-29,Bengaluru,Suite,Walk-in,Corporate,Male,25,1.0,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19,Pune,Suite,Corporate,Corporate,Other,50,4.0,...,1.2,1,0,1,Credit Card,66334.52,15575.345296,12689.793676,40212.657465,10546.517239
3,BKG01079,Customer_1079,2025-12-14,Mumbai,Deluxe,Walk-in,Regular,Male,53,3.0,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,4642.602312,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20,Delhi,Suite,Travel Agent,Budget,Male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,3508.296660,6545.581304,3979.308676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,BKG01738,Customer_1738,2025-11-27,Hyderabad,Deluxe,Online,Premium,Other,52,3.0,...,4.0,4,1,0,Net Banking,12777.78,204.444480,4191.111840,9277.794053,3295.541467
2021,BKG01193,Customer_1193,2025-10-22,Hyderabad,Deluxe,Online,Premium,Male,33,5.0,...,4.7,5,1,1,Net Banking,51298.55,17574.883230,9861.000000,22307.978333,11415.688437
2022,BKG01210,Customer_1210,2025-07-11,Mumbai,Deluxe,Online,Premium,Male,48,6.0,...,1.3,6,1,0,Debit Card,79546.56,23108.275680,9406.380720,36544.131723,19894.152597
2023,BKG01060,Customer_1060,2025-01-24,Hyderabad,Executive,Travel Agent,Budget,Female,52,2.0,...,3.8,2,1,1,Debit Card,18041.10,5910.264360,6065.417820,9683.417958,2447.417682
2024,BKG00642,Customer_0642,2025-04-06,Mumbai,Suite,Walk-in,Premium,Male,23,5.0,...,4.8,1,1,1,Debit Card,7644.65,1025.147565,1323.900487,3428.758380,3190.744055

In [13]:
## 27. Fix extreme or impossible Age values
Explanation: Ages such as 150, 120, or 100 are unrealistic for hotel customers. Set a
reasonable range (e.g., 18–90) and replace values outside it with missing.

SyntaxError: invalid character '–' (U+2013) (2299173135.py, line 3)

In [42]:
df['Age'].unique()

array(['39', '25', '50', '53', '38', '35', '33', '65', '48', '47', '52',
       '44', nan, '29', '49', '34', '58', '42', '19', '28', '62', '64',
       '21', '26', '57', '22', '59', '54', '46', '31', '67', '24', '68',
       '32', '27', '56', '36', '61', '100', '60', '43', '20', '66', '51',
       '30', '40', '18', '23', '63', '45', '69', '41', '150', '37', '55',
       '120', 'unknown', '45Y', '25 years', '30 yrs'], dtype=object)

In [ ]:
df['Age']=df['Age'].replace({
    '45Y':'45',
    '25 years':''
})

In [14]:
## 28. Handle missing Gender values
Explanation: Some rows have blank Gender. You can fill with “Unknown”, drop the rows, or
leave them as missing depending on your analysis needs.

SyntaxError: invalid character '“' (U+201C) (2837418276.py, line 2)

In [15]:
## 29. Correct obvious typos in categorical columns
Explanation: Examples include delux → Deluxe, exec → Executive, Hydrabad → Hyderabad,
Bangalore → Bengaluru. Fixing these improves grouping and reporting accuracy.

SyntaxError: invalid character '→' (U+2192) (3873767697.py, line 2)

In [16]:
## 30. Decide how to treat rows with too many missing values
Explanation: Some rows are missing Customer Name, City, Room Type, Age, and other
important fields at the same time. Decide a threshold (e.g., more than 40% missing) and
drop or flag those incomplete rows.

SyntaxError: invalid syntax (1786609995.py, line 2)