In [46]:
import pandas as pd
df=pd.read_csv(r"C:\Users\LENOVO\Downloads\indian-job-market-dataset-2025.csv")
df.head()
df.shape

(97929, 17)

In [47]:
df. columns

Index(['title', 'jobId', 'currency', 'jobUploaded', 'companyName',
       'tagsAndSkills', 'experience', 'salary', 'location', 'companyId',
       'ReviewsCount', 'AggregateRating', 'jobDescription', 'minimumSalary',
       'maximumSalary', 'minimumExperience', 'maximumExperience'],
      dtype='object')

In [48]:
df.columns=df.columns.str.title()
df.columns

Index(['Title', 'Jobid', 'Currency', 'Jobuploaded', 'Companyname',
       'Tagsandskills', 'Experience', 'Salary', 'Location', 'Companyid',
       'Reviewscount', 'Aggregaterating', 'Jobdescription', 'Minimumsalary',
       'Maximumsalary', 'Minimumexperience', 'Maximumexperience'],
      dtype='object')

In [49]:
df.head(2)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              97929 non-null  object
 1   Jobid              97929 non-null  int64
 2   Currency           97929 non-null  object
 3   Jobuploaded        97929 non-null  object
 4   Companyname        97925 non-null  object
 5   Tagsandskills      97358 non-null  object
 6   Experience         95824 non-null  object
 7   Salary             97929 non-null  object
 8   Location           97929 non-null  object
 9   Companyid          97929 non-null  int64
 10  Reviewscount       62677 non-null  float64
 11  Aggregaterating    62677 non-null  float64
 12  Jobdescription     97929 non-null  object
 13  Minimumsalary      97358 non-null  float64
 14  Maximumsalary      97358 non-null  float64
 15  Minimumexperience  97358 non-null  float64
 16  Maximumexperience  97358 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 12.7+ MB

In [50]:
df.isna().sum()

Title                    0
Jobid                    0
Currency                 0
Jobuploaded              0
Companyname              4
Tagsandskills          571
Experience            2105
Salary                   0
Location                 0
Companyid                0
Reviewscount         35252
Aggregaterating      35252
Jobdescription           0
Minimumsalary          571
Maximumsalary          571
Minimumexperience      571
Maximumexperience      571
dtype: int64

In [51]:
print(df['Title'].unique())
print("missing value:",df['Title'].isna().sum())
print("_"*40)
print("duplicated:",df['Title'].duplicated().sum())
print("_"*40)
print("check duplicated:",df['Title'].value_counts().head(10))

['Sr. HR Recruiter (NON IT)' 'Fire And Safety Officer'
 'Opening For Performance Marketing - Chennai' ...
 'Sr.Executive/Asst. Manager - Pricing   - Sea Export'
 'CNC Machine Maintenance Engineer @ Manali, Chennai'
 'IT Cum Digital Marketing Executive']
missing value: 0
________________________________________
duplicated: 42825
________________________________________
check duplicated: Title
Application Developer             2039
Application Lead                  1347
Sales Executive                    576
Software Development Engineer      497
Business Development Executive     457
Trust & Safety New Associate       348
Data Engineer                      339
Business Development Manager       323
Sales Manager                      319
Java Full Stack Developer          283
Name: count, dtype: int64

In [52]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [53]:
# check jobid columns
print("missing value:",df['Jobid'].isna().sum())
print("-"*40)

print("unique:",df['Jobid'].unique())
print("-"*40)

print("duplicate:",df['Jobid'].duplicated().sum())
print("-"*40)

print("count duplicate:",df['Jobid'].value_counts())

missing value: 0
----------------------------------------
unique: [270925008041 270925007584 270925007492 ... 270925008467 270925008099
 270925008094]
----------------------------------------
duplicate: 250
----------------------------------------
count duplicate: Jobid
230925928900    2
230925026361    2
280925003063    2
230925507720    2
290925500734    2
               ..
11025024237     1
11025024265     1
11025500011     1
11025500015     1
270925008094    1
Name: count, Length: 97679, dtype: int64

In [54]:
# check Currency columns
print("missing value:",df['Currency'].isna().sum())
print("-"*50)

print("duplicated:",df['Currency'].duplicated().sum())
print("-"*50)

print("unique value:",df['Currency'].unique())

missing value: 0
--------------------------------------------------
duplicated: 97927
--------------------------------------------------
unique value: ['INR' 'USD']

In [55]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [56]:
# check Jobuploaded columns
print("missing value:",df['Jobuploaded'].isna().sum())
print("-"*50)

print("unique:",df['Jobuploaded'].unique())
print("-"*50)

print("duplicated:",df['Jobuploaded'].duplicated().sum())
print("-"*50)
#df['Jobuploaded']=pd.to_datetime(df['Jobuploaded'],errors="coerce")
#df['Jobuploaded']

missing value: 0
--------------------------------------------------
unique: ['6 Days Ago' 'Few Hours Ago' 'Just Now' '3 Days Ago' '4 Days Ago'
 '1 Day Ago' '2 Days Ago' '7 Days Ago' '5 Days Ago' 'Today' '8 Days Ago'
 'Starts in 1-3 months' '9 Days Ago' '10 Days Ago' 'Starts within 1 month'
 "Starts : 6th Oct' 25" "Starts : 3rd Nov' 25" "Starts : 8th Oct' 25"
 'Starts in 3-6 months' "Starts : 10th Oct' 25" "Starts : 7th Oct' 25"
 "Starts : 20th Oct' 25" "Starts : 22nd Oct' 25" "Starts : 25th Nov' 25"
 "Starts : 15th Oct' 25" "Starts : 15th Jan' 26" "Starts : 14th Oct' 25"
 '15 Days Ago' '20 Days Ago' "Starts : 1st Nov' 25"]
--------------------------------------------------
duplicated: 97899
--------------------------------------------------

In [57]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [58]:
# check Companyname
print("missing value:",df['Companyname'].isna().sum())
print("*"*40)

# Find most frequent company
company_mode = df["Companyname"].mode()[0]
df['Companyname']=df['Companyname'].fillna(company_mode)
print("fill with mode:",df['Companyname'])

print("*"*40)
print("missing value:",df['Companyname'].isna().sum())
print("*"*40)

# check duplicated
print("duplicated:",df['Companyname'].duplicated().sum())
print("*"*40)
# remove extra space
df['Companyname']=df['Companyname'].str.strip()
df['Companyname']

missing value: 4
****************************************
fill with mode: 0                                                    Orion
1        Apollo Hospitals International Limited, Ahmedabad
2                                  TVS Credit Services Ltd
3                                      GNR Global Services
4                                   Cadila Pharmaceuticals
                               ...
97924                                            GSH Group
97925                       Luxus Green Mobility Pvt. Ltd.
97926                               Cadila Pharmaceuticals
97927                                  GNR Global Services
97928                               Logon Global Solutions
Name: Companyname, Length: 97929, dtype: object
****************************************
missing value: 0
****************************************
duplicated: 79261
****************************************

0                                                    Orion
1        Apollo Hospitals International Limited, Ahmedabad
2                                  TVS Credit Services Ltd
3                                      GNR Global Services
4                                   Cadila Pharmaceuticals
                               ...
97924                                            GSH Group
97925                       Luxus Green Mobility Pvt. Ltd.
97926                               Cadila Pharmaceuticals
97927                                  GNR Global Services
97928                               Logon Global Solutions
Name: Companyname, Length: 97929, dtype: object

In [59]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [60]:
# check the Tagsandskills columns
print("missing value:",df['Tagsandskills'].isna().sum())
print("_"*50)

missing value: 571
__________________________________________________

In [61]:
#remove missing value using fillna
value=df['Tagsandskills'].mode()[0]
df['Tagsandskills']=df['Tagsandskills'].fillna(value)
print("fill missing value:",df['Tagsandskills'])
print("_"*50)

# after fill check missing value
print("missing value:",df['Tagsandskills'].isna().sum())
print("_"*50)

# check duplicated value
print("duplicated:",df['Tagsandskills'].duplicated().sum())
print("_"*50)
#check how many duplicated have each columns
df['Tagsandskills'].value_counts().head(10)

fill missing value: 0        Communication,Manpower,Staffing,Convincing Pow...
1        Safety Officer Activities,Fire Protection,Fire...
2        Performance Marketing,User Acquisition,growth ...
3        Fluent English,Spoken English,Good English Com...
4        Product Marketing,CNS,Product Management,Nephr...
                               ...
97924    CNC Maintenance,CNC Machines,Electrical Mainte...
97925    Google AdWords,Digital Marketing,Social Media ...
97926    Analytical Method Validation,Analytical Method...
97927    Fluent English,Spoken English,Strong Communica...
97928    Client Support,English,Client Coordination,Mal...
Name: Tagsandskills, Length: 97929, dtype: object
__________________________________________________
missing value: 0
__________________________________________________
duplicated: 13622
__________________________________________________

Tagsandskills
Retail,Lead generation,Forex,Investment products,Sales,Customer satisfaction,Business Development Associate,Financial services                   687
bde,cold calling,business development,business development management,financial services,corporate sales,sales,marketing                         110
Loans,Networking,Branch banking,Relationship building,Anti money laundering,Customer service,Customer engagement,Internet banking                 77
customer service,creative writing,moderation,content writing,stress analysis,digital marketing,market research,content management                 77
customer service,moderation,content writing,stress analysis,business process outsourcing,non voice process,market research,content management     74
business loan,business development,sales,marketing,direct selling,channel sales,team handling,loan against property                               58
Object Oriented technology,TOGAF,J2EE technology,OBRM,Service-Oriented Architecture,C/C++,SOA,E-TOM Architecture                                  52
Medical Coding,HCPCS,Clinical Research,CPT,Medical Transcription,CPC,ICD,Cpt Coding                                                               43
SAP ABAP,OData,SAP FICA,Adobe Forms,Smart Forms,collections,invoicing,SAP S/4HANA                                                                 42
trade finance,sales,marketing,trade,secondary sales,foreign exchange,forex operations,import                                                      41
Name: count, dtype: int64

In [62]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [63]:
# check Experience columns
print("missing value:",df['Experience'].isna().sum())

missing value: 2105

In [64]:
# fill the missing value using mode
fill=df['Experience'].mode()[0]
# fill missing value
df['Experience']=df['Experience'].fillna(fill)
df['Experience']
print("-"*50)
# check missing value
print("after fill missing value is:",df['Experience'].isna().sum())
print("-"*50)
# check duplicated value
print("duplicated:",df['Experience'].duplicated().sum())

--------------------------------------------------
after fill missing value is: 0
--------------------------------------------------
duplicated: 97642

In [65]:
#check Salary columns
# check missing value
print("missing value:",df['Salary'].isna().sum())
print("-"*50)

# check  duplicated
print("duplicated:",df['Salary'].duplicated().sum())
print("-"*50)

# check unique value 
print("unique:",df['Salary'].unique())

missing value: 0
--------------------------------------------------
duplicated: 96590
--------------------------------------------------
unique: ['2-4 Lacs PA' '3-5 Lacs PA' 'Not disclosed' ... '9-10.08 Lacs PA'
 '36,000-48,000 PA' '1.92-3.36 Lacs PA']

In [66]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [67]:
# check Location columns
print("missing value:",df['Location'].isna().sum())
print("*"*50)

# check duplicated
print("duplicated:",df['Location'].duplicated().sum())
print("*"*50)

# check unique value
print("unique:",df['Location'].unique())

missing value: 0
**************************************************
duplicated: 87863
**************************************************
unique: ['Kolkata(Chinar Park)' 'Gandhinagar, Ahmedabad' 'Chennai' ...
 'Bengaluru(Hennur +2)' 'Ahmedabad(Sindhu Bhavan Road +1)'
 'Jammu(Nanak Nagar)']

In [68]:
# check Companyid
# check missing value
print("missing value:",df['Companyid'].isna().sum())
print("-"*50)

# check duplicated
print("duplicated:",df['Companyid'].duplicated().sum())
print("-"*50)

# check data type
print("dtype:",df['Companyid'].dtype)
print("-"*50)

print(df['Companyid'].nunique())
print("-"*50)

# remove space
#print(df['Companyid'].str.strips())

missing value: 0
--------------------------------------------------
duplicated: 79601
--------------------------------------------------
dtype: int64
--------------------------------------------------
18328
--------------------------------------------------

In [69]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [70]:
# check Reviewscount coljumns
# check missing value
print("missing value:",df['Reviewscount'].isna().sum())
print("-"*50)
# check datatype
print("data type:",df['Reviewscount'].dtype)
print("-"*50)

# fill missing value
df['Reviewscount']=df['Reviewscount'].fillna(0)
print("after fill missing value:",df['Reviewscount'])
print("-"*50)

# check duplicated
print("duplicated:",df['Reviewscount'].duplicated().sum())

missing value: 35252
--------------------------------------------------
data type: float64
--------------------------------------------------
after fill missing value: 0           0.0
1        5162.0
2        2892.0
3           0.0
4        2134.0
          ...
97924     284.0
97925      13.0
97926    2134.0
97927       0.0
97928       4.0
Name: Reviewscount, Length: 97929, dtype: float64
--------------------------------------------------
duplicated: 96553

In [71]:
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimumsalary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,0.0,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0

In [72]:
# check missing value
print("missing value:",df['Aggregaterating'].isna().sum())
print("-"*50)

missing value: 35252
--------------------------------------------------

In [73]:
# check  Aggregaterating columns
# check datatype
print("dtype:",df['Aggregaterating'].dtype)
print("-"*50)


# check how percentage missing value have
print("Missing %:", df['Aggregaterating'].isna().mean() * 100)
print("-"*50)

# fill missing value with using median
df['Aggregaterating']=df['Aggregaterating'].fillna(df['Aggregaterating'].median())
print(df['Aggregaterating'])
# check duplicated
print("duplicated:",df['Aggregaterating'].duplicated().sum())
print("-"*50)

# after fill missing value check missing value
print("after fill missing value:",df['Aggregaterating'].isna().sum())

dtype: float64
--------------------------------------------------
Missing %: 35.99750839894209
--------------------------------------------------
0        3.7
1        4.0
2        4.2
3        3.7
4        3.4
        ...
97924    4.2
97925    2.6
97926    3.4
97927    3.7
97928    4.2
Name: Aggregaterating, Length: 97929, dtype: float64
duplicated: 97888
--------------------------------------------------
after fill missing value: 0

In [74]:
# check Jobdescription columns
print("missing value:",df['Jobdescription'].isna().sum())
print("="*50)

# check datatypes
print("dtype:",df['Jobdescription'].dtype)
print("-"*50)
# remove space 
df['Jobdescription'].str.strip()

# check unique value
print("unique:",df['Jobdescription'].unique())
print("_"*50)

# convert into title case
df['Jobdescription']=df['Jobdescription'].str.title()
df['Jobdescription']

missing value: 0
==================================================
dtype: object
--------------------------------------------------
unique: ['Preferred candidate profile . .'
 'Ensure active Fire Protection System,such as Fire Hydrant system,Fire extinguishers,Fire Alarm smoke detector system,Sprinkler system keep in good condition'
 'MBA Marketing (preferred Tier II or III B- School). <br><br>Experience <br><br> 12+ years exp in Digital Marketing with a focus on performance marketing/ content strategy / campaign management along with team handling experience<br><br>Mobility Experience / development of mobile sites / Apps'
 ... 'Documentation as per GLP requirement'
 'Job title-Customer Care Associate\nJob location-Chandigarh\nSalary-22-23in hand\n\nQualification-Graduated/Postgraduated\nRotational shifts\nFluent english\nCab facility\n\n\nCall at 6239334478'
 '<p> <strong>Role:</strong> Primary advisor for study abroad candidates.</p><ul><li><strong>Focus:</strong> Deliver high-touch client service.</li><li><strong>Duties:</strong> Counsel on courses/visas; manage applications; ensure high satisfaction.</li><li><strong>Goal:</strong> Drive successful enrolment and retention.</li></ul>']
__________________________________________________

0                          Preferred Candidate Profile . .
1        Ensure Active Fire Protection System,Such As F...
2        Mba Marketing (Preferred Tier Ii Or Iii B- Sch...
3        Job Title-Medical Billing Executive\nLocation-...
4        Principal Tasks & Responsibilities : (Please W...
                               ...
97924    Experience: Minimum 2+ Years In Cnc Machine El...
97925    <P> </P><P><Strong>Position Overview :-</Stron...
97926                 Documentation As Per Glp Requirement
97927    Job Title-Customer Care Associate\nJob Locatio...
97928    <P> <Strong>Role:</Strong> Primary Advisor For...
Name: Jobdescription, Length: 97929, dtype: object

In [75]:
import numpy as np

# Rename column
df = df.rename(columns={"Minimumsalary": "Minimum_salary"})

# Check missing values
print("Missing values:", df['Minimum_salary'].isna().sum())
print("*" * 50)

# Check zero values BEFORE filling anything
zero_count = (df['Minimum_salary'] == 0).sum()
zero_percentage = (df['Minimum_salary'] == 0).mean() * 100

print("Zero values:", zero_count)
print("Zero percentage:", zero_percentage)
print("*" * 50)

# If 0 means salary not disclosed/unavailable,
# convert 0 to NaN
df['Minimum_salary'] = df['Minimum_salary'].replace(0, np.nan)

# Check missing values after replacing 0
print("Missing after replacing 0:",
      df['Minimum_salary'].isna().sum())

print("Missing percentage:",
      df['Minimum_salary'].isna().mean() * 100)

Missing values: 571
**************************************************
Zero values: 64129
Zero percentage: 65.48519846010885
**************************************************
Missing after replacing 0: 64700
Missing percentage: 66.06827395357861

In [76]:
print("Missing values:", df['Minimum_salary'].isna().sum())
print("*" * 50)
df['Minimum_salary'] = df['Minimum_salary'].fillna(df['Minimum_salary'].median())
df['Minimum_salary']

Missing values: 64700
**************************************************

0        200000.0
1        300000.0
2        300000.0
3         70000.0
4        800000.0
           ...
97924     50000.0
97925    300000.0
97926    300000.0
97927     70000.0
97928    192000.0
Name: Minimum_salary, Length: 97929, dtype: float64

In [77]:
print("Missing values:", df['Minimum_salary'].isna().sum())

Missing values: 0

In [78]:
df.head(80)
# check unique value
print("unique:", df['Minimum_salary'].unique()[:25])
# chenge data type
df['Minimum_salary']=df['Minimum_salary'].astype(int)
df['Minimum_salary']

unique: [ 200000.  300000.   70000.  800000.  350000.   50000.  600000.  450000.
  475000. 1000000.  700000.  400000.  150000.  325000. 2000000.  900000.
  375000.   80000.  250000.  144000.  500000.  100000.  550000. 3000000.
 1400000.]

0        200000
1        300000
2        300000
3         70000
4        800000
          ...
97924     50000
97925    300000
97926    300000
97927     70000
97928    192000
Name: Minimum_salary, Length: 97929, dtype: int64

In [79]:
df.head(50)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimum_salary,Maximumsalary,Minimumexperience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,0.0,3.7,Preferred Candidate Profile . .,200000,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure Active Fire Protection System,Such As F...",300000,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,Mba Marketing (Preferred Tier Ii Or Iii B- Sch...,300000,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,0.0,3.7,Job Title-Medical Billing Executive\nLocation-...,70000,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please W...,800000,1800000.0,5.0,10.0
5,Senior Accountant,270925007323,INR,6 Days Ago,Vedaant Techno Art,"Tds Filing,ITR,Gst Filing,Balance Sheet Finali...",10-15 Yrs,3.5-6 Lacs PA,"Noida, Greater Noida",124725375,0.0,3.7,Preferred Candidate Profile <Br><Br>Experience...,350000,600000.0,10.0,15.0
6,Maintenance Technician,270925007180,INR,6 Days Ago,Avalon Technologies,"Booth,Conveyor,Special Process,Utility Mainten...",3-5 Yrs,Not disclosed,"Sriperumbudur, Chennai, Kanchipuram",30971,571.0,3.7,<P><Strong>Job Description</Strong></P><P> </P...,300000,0.0,3.0,5.0
7,Officer/Engineer Technical,270925006659,INR,6 Days Ago,Balkrishna Industries (BKT),"M.S Office,SAP,Computer Skills,MS Office,Techn...",2-3 Yrs,Not disclosed,Aurangabad(Waluj),123591869,462.0,4.1,Ready To Work In All Shifts . Understanding Of...,300000,0.0,2.0,3.0
8,Officer- Technical Lab,270925006525,INR,6 Days Ago,Balkrishna Industries (BKT),"SAP,Laboratory Knowledge,Microsoft,Technical,Lab",2-4 Yrs,Not disclosed,Aurangabad(Waluj),123591869,462.0,4.1,Preferred Candidate Profile . Tyre Industry Ex...,300000,0.0,2.0,4.0
9,Site Reliability Engineer,270925006315,INR,6 Days Ago,Coforge,"Sre,Azure Devops,Monitoring Tools,Site,Site Re...",4-14 Yrs,Not disclosed,"New Delhi, Gurugram, Greater Noida",24468,5904.0,3.2,Develop Automation Scripts Using Python Or Oth...,300000,0.0,4.0,14.0
10,Hiring For Voice & Chat Process,270925006180,INR,6 Days Ago,GNR Global Services,"BPO,Domestic Voice Process,Non Voice Process,D...",0-4 Yrs,"50,000-1.75 Lacs PA","Mohali, Chandigarh",123804403,0.0,3.7,Hiring For Voice & Chat Process\nJob Location:...,50000,175000.0,0.0,4.0
11,Talent Acquisition Professional,270925005692,INR,6 Days Ago,Knorr Bremse,"Blue Collar Hiring,Talent Acquisition,Recruitm...",7-10 Yrs,Not disclosed,"Palwal, Faridabad",1021754,937.0,3.5,Preferred Candidate Profile . 7 To 10 Years In...,300000,0.0,7.0,10.0
12,Hiring For Chat Process,270925005277,INR,6 Days Ago,GNR Global Services,"Chat Support,US Process,Customer Support,Custo...",0-4 Yrs,"50,000-2.5 Lacs PA","Mohali, Chandigarh",123804403,0.0,3.7,Hiring For Chat Process\nJob Location: Mohali/...,50000,250000.0,0.0,4.0
13,HR Recruiter | Regional Recruiter | Jaipur,270925005267,INR,6 Days Ago,TVS Credit Services Ltd,"NBFC,Bulk Hiring,Sales Hiring,Non IT Recruitme...",3-8 Yrs,Not disclosed,Jaipur,1324750,2892.0,4.2,Preferably Male Candidates With (Nbfc / Bfsi H...,300000,0.0,3.0,8.0
14,MEP Billing Engineer (Jaipur),270925004781,INR,6 Days Ago,Pacific Development Corporation,"Mep Billing Engineer,Mep Billing,Site Billing,...",8-10 Yrs,Not disclosed,Jaipur,6944403,185.0,3.5,Ensure That Only Quality-Compliant And Approve...,300000,0.0,8.0,10.0
15,JOB For MALE |Fraud Prevention Credit card || ...,270925004697,INR,6 Days Ago,Manpowergroup Services India,"Compliance Monitoring,Credit Card Fraud,Fraud ...",1-6 Yrs,3-4.5 Lacs PA,Chennai(Poonamallee +1),742,0.0,3.7,<P> </P><P><Strong>Job Title:</Strong> Executi...,300000,450000.0,1.0,6.0
16,Pole Deployment Engineer (Off Role),270925004651,INR,6 Days Ago,Indus Towers,"Fiber Optics,Ftth,Fttx,NLD,Deployment,Tower Er...",2-7 Yrs,2-4.5 Lacs PA,"Panipat, Sirsa, Hisar",481769,2594.0,3.6,<P><Strong>1.Daily Liaison With Partner On Exe...,200000,450000.0,2.0,7.0
17,"Senior Engineer-Mechanical (Planning/Billing),...",270925000122,INR,6 Days Ago,ALP Talent Solutions,"Mechanical,Billing,Planning,Billing Engineerin...",5-8 Yrs,6-9 Lacs PA,Varanasi,125125399,0.0,3.7,Minimum 5 Years Experience In Steel Detailing ...,600000,900000.0,5.0,8.0
18,Design Engineer-Mechanical/Civil (Fabrication ...,270925000101,INR,6 Days Ago,ALP Talent Solutions,"Tekla,AutoCAD,Mechanical Design,Solid Works,Bo...",3-7 Yrs,4.5-6 Lacs PA,Varanasi,125125399,0.0,3.7,Proficiency In Autocad / Tekla / Bocad (Certif...,450000,600000.0,3.0,7.0
19,Design Manager-Mechanical/Civil (Fabrication D...,270925000088,INR,6 Days Ago,ALP Talent Solutions,"Tekla,AutoCAD,Mechanical Design,Solid Works,Bo...",8-12 Yrs,6-12 Lacs PA,Varanasi,125125399,0.0,3.7,<P> Job Title: Design Manager- Mechanical/ Ci...,600000,1200000.0,8.0,12.0
20,Cardiologist For Nalgonda & Vijayawada,270924016565,INR,Few Hours Ago,Kamineni Hospitals,"Angiography,Interventional Cardiology,2D Echo,...",0-5 Yrs,2-4.75 Lacs PA,"Vijayawada, Nalgonda",519155,223.0,4.1,The Interventional Cardiologist Should Be High...,200000,475000.0,0.0,5.0
21,International Voice Process || Customer Care &...,270825021863,INR,Just Now,Cogenthub,"International BPO,Fluent English,Customer Serv...",0-5 Yrs,4.75-5 Lacs PA,Gurugram,123473819,384.0,3.4,<P> </P><P> <Strong>Hiring Alert Internationa...,475000,500000.0,0.0,5.0
22,Assistant Manager- Bakery,270825005762,INR,3 Days Ago,Bunge,"Bakery,shift,Assistance,Management",8-13 Yrs,10-13 Lacs PA,Nellore,6187488,688.0,3.9,Votator Operation Experience And Knowledge Abo...,1000000,1300000.0,8.0,13.0
23,Walk In Drive @Noida | Quality Analyst | TELUS...,270525026436,INR,4 Days Ago,TELUS International,"Call Audit,Quality Audit,Call Monitoring,Call ...",5-10 Yrs,Not disclosed,Noida,6549678,1603.0,3.6,<P><U><Strong>Role & Responsibilities</Strong>...,300000,0.0,1.0,5.0
24,4LPA CTC For Email Chat Backend & Non Voice Pr...,270525001120,INR,1 Day Ago,Human Before Resource,"Blended Process,Customer Service,Non Voice,Ema...",0-5 Yrs,Not disclosed,"Kolkata, Rajarhat, Newtown",2892790,0.0,3.7,We Are Hiring Chat Process Executive (Fresher ...,300000,0.0,0.0,5.0
25,Embryologist,270225007394,INR,2 Days Ago,Ang Placement And Staffing Solutions,"Embryologist,Sperm Collection and Preparation,...",0-5 Yrs,7-11 Lacs PA,"Jalandhar, Noida, Gurugram",1412850,0.0,3.7,"<Br /><P><Strong><U>Dear Embryologist,</U></St...",700000,1100000.0,0.0,5.0
26,Billing Engineer,260925923439,INR,7 Days Ago,Vedanta Enterprises,"Bill Verification,Measurement,TDS,Civil Billin...",10-15 Yrs,Not disclosed,"Ahmedabad, Shilaj",124727963,0.0,3.7,"Contractor And Subcontractor Bills,Work Certif...",300000,0.0,10.0,15.0
27,ATM Implementation - Software Engineer / Senio...,260925914626,INR,7 Days Ago,Euronet Services India,"ATM Implementation,Linux,BNA System,Screen Des...",4-8 Yrs,Not disclosed,Thane,830623,166.0,3.7,<P><Strong>Experience</Strong>: 4 - 8 Years Of...,300000,0.0,4.0,8.0
28,Software Engineer Implementation,260925914625,INR,7 Days Ago,Euronet Services India,"ISO8583,Finsim,EFT,PoS,ATM,Tandem,Postilion,Base",3-8 Yrs,Not disclosed,Thane,830623,166.0,3.7,Iso 8583 Experience,300000,0.0,3.0,8.0
29,Relationship Manager - Key Partnership Group,260925504548,INR,7 Days Ago,Tata AIG General Insurance Company,"insurance,upselling,new business,health insura...",2-7 Yrs,Not disclosed,Jodhpur,5105204,2949.0,4.1,Disclaimer: This Job Description Has Been Sour...,300000,0.0,2.0,7.0
30,Deputy Manager - Health Claims,260925504547,INR,7 Days Ago,Tata AIG General Insurance Company,"insurance,tpa,mediclaim,health insurance,us he...",3-6 Yrs,Not disclosed,Kolkata,5105204,2949.0,4.1,Contribute To The Development And Implementati...,300000,0.0,3.0,6.0
31,Manager - Production,260925504385,INR,7 Days Ago,Caterpillar Inc,"Product quality,Manager Quality Assurance,Anal...",5-9 Yrs,Not disclosed,Aurangabad,124443920,1516.0,4.2,Ability To Perform Day-To-Day Operations Of A ...,300000,0.0,5.0,9.0
32,FGW Product Manager,260925504384,INR,7 Days Ago,Caterpillar Inc,"Relationship management,Product management,Sal...",10-15 Yrs,Not disclosed,Aurangabad,124443920,1516.0,4.2,Bachelor Degree In Technical Field Or Business...,300000,0.0,10.0,15.0
33,Engineer Design (Engine Core Components),260925504383,INR,7 Days Ago,Caterpillar Inc,"CFD,Prototype,Simulation,Project management,An...",5-10 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,Lead Engineering Activities Across The Entire...,300000,0.0,5.0,10.0
34,Engineer - Design (Engine Installation & Cooling),260925504382,INR,7 Days Ago,Caterpillar Inc,"Architecture,Analytical,Manager Technology,Pro...",8-13 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,Shifts Focus Among Several Efforts As Required...,300000,0.0,8.0,13.0
35,Embedded Software Engineering Specialist,260925504381,INR,7 Days Ago,Caterpillar Inc,"Post production,software architecture,Producti...",12-15 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,Bachelor S Or Master S Degree In Computer Scie...,300000,0.0,12.0,15.0
36,Design Engineer (Engine Installation & Cooling),260925504380,INR,7 Days Ago,Caterpillar Inc,"Architecture,Analytical,Manager Technology,Pro...",4-9 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,Shifts Focus Among Several Efforts As Required...,300000,0.0,4.0,9.0
37,Design Engineer - Configuration,260925504379,INR,7 Days Ago,Caterpillar Inc,"Fabrication,Geometry,Team management,Analytica...",3-7 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,"Experience With Vpd Analysis,Biq,Apqp,And Cost...",300000,0.0,3.0,7.0
38,Customer Services Consultant,260925504377,INR,7 Days Ago,Caterpillar Inc,"Relationship management,Mining,Condition monit...",9-14 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,. Minimum Of 9 Years Of Hands-On Experience I...,300000,0.0,9.0,14.0
39,Associate Engineer- Structural Design (Mining ...,260925504376,INR,7 Days Ago,Caterpillar Inc,"Mining,Prototype,Project management,Analytical...",6-10 Yrs,Not disclosed,Chennai,124443920,1516.0,4.2,Good Understanding Of Geometric Dimensioning A...,300000,0.0,6.0,10.0
40,AVP,260925504173,INR,7 Days Ago,Barclays,"SAP,Data management,Financial reporting,Projec...",4-5 Yrs,Not disclosed,Chennai,1227558,1143.0,3.9,<Div> Join Us As An Assistant Vice President A...,300000,0.0,4.0,5.0
41,Assistant Manager - Risk Utility,260925504172,INR,7 Days Ago,Barclays,"Relationship management,Enterprise risk manage...",4-5 Yrs,Not disclosed,Noida,1227558,1143.0,3.9,Join Us As An Assistant Manager Risk Utility A...,300000,0.0,4.0,5.0
42,Senior Decision Analyst- Marketing Measurement...,260925504146,INR,7 Days Ago,Barclays,"data cleansing,Data analysis,Analytical,Data q...",5-10 Yrs,Not disclosed,"Noida, Gurugram",1227558,1143.0,3.9,You May Be Assessed On The Key Critical Skills...,300000,0.0,5.0,10.0
43,Legal Officer - Asia,260925504131,INR,7 Days Ago,World Bank,"International Law,General Counsel,Counsellor,L...",2-7 Yrs,Not disclosed,Chennai,792848,101.0,3.9,Applicants Should Also Be Able To Provide Seco...,300000,0.0,2.0,7.0
44,Regional Business Manager,260925503843,INR,7 Days Ago,NOVARTIS,"Networking,Trade sales,Cardiovascular,Pharma,D...",8-10 Yrs,Not disclosed,Chandigarh,1344828,1858.0,4.1,<Div> The Regional Business Manager/First Line...,300000,0.0,8.0,10.0
45,Branch:Branch Relationship Officer,260925503831,INR,7 Days Ago,Axis Bank,"Loans,Networking,Branch banking,Relationship b...",2-4 Yrs,Not disclosed,Alipurduar,1613304,29961.0,3.7,Complete All Mandatory Certifications Required...,300000,0.0,2.0,4.0
46,RB-LS: Business Development Associate,260925503827,INR,7 Days Ago,Axis Bank,"Retail,Lead generation,Forex,Investment produc...",1-6 Yrs,Not disclosed,Surat,1613304,29961.0,3.7,Officer Sales-2 : Graduate With More Than 1 Ye...,300000,0.0,1.0,6.0
47,RB-LS: Business Development Associate,260925503826,INR,7 Days Ago,Axis Bank,"Retail,Lead generation,Forex,Investment produc...",1-6 Yrs,Not disclosed,Patna,1613304,29961.0,3.7,Officer Sales-2 : Graduate With More Than 1 Ye...,300000,0.0,1.0,6.0
48,RB-LS: Business Development Associate,260925503825,INR,7 Days Ago,Axis Bank,"Retail,Lead generation,Forex,Investment produc...",1-6 Yrs,Not disclosed,Jamshedpur,1613304,29961.0,3.7,Officer Sales-2 : Graduate With More Than 1 Ye...,300000,0.0,1.0,6.0
49,Branch:Gold Loan Officer,260925503824,INR,7 Days Ago,Axis Bank,"Usage,Team management,Publishing,NBFC,Branch b...",2-4 Yrs,Not disclosed,Kothagudem,1613304,29961.0,3.7,Solid Relationship Building Skills With Experi...,300000,0.0,2.0,4.0

In [80]:
# check Maximumsalary columns
# rename name  columns name
df=df.rename(columns={"Maximumsalary":"Maximum_salary"})
df
# check missing value
print("missing value:",df['Maximum_salary'].isna().sum())
print("*"*50)
# check how many 0 value have this columns
zero_count=(df['Maximum_salary'] == 0).sum()
print("zero_count:",zero_count)
print("*"*50)

# check 0 peracentage 
zero_per=(df['Maximum_salary']==0).mean() * 100
print("zero_per:",zero_per)
print("*"*50)

# convert them into NaN value
df['Maximum_salary']=df['Maximum_salary'].replace(0,np.nan)
df['Maximum_salary']

missing value: 571
**************************************************
zero_count: 64121
**************************************************
zero_per: 65.47702927631242
**************************************************

0         400000.0
1         500000.0
2              NaN
3         200000.0
4        1800000.0
           ...
97924     200000.0
97925          NaN
97926          NaN
97927     200000.0
97928     336000.0
Name: Maximum_salary, Length: 97929, dtype: float64

In [81]:
# after covert nan check missing value
print("mussing value:",df['Maximum_salary'].isna().sum())
print("-"*50)

mussing value: 64692
--------------------------------------------------

In [82]:
# fill then into  median
df['Maximum_salary']=df['Maximum_salary'].fillna(df['Maximum_salary'].median())
print("missing value:",df['Maximum_salary'])
print("-"*50)
print("mussing value:",df['Maximum_salary'].isna().sum())
print("-"*50)

# convert datatype float to  int
df['Maximum_salary']=df['Maximum_salary'].astype(int)
print("astype:",df['Maximum_salary'])

missing value: 0         400000.0
1         500000.0
2         550000.0
3         200000.0
4        1800000.0
           ...
97924     200000.0
97925     550000.0
97926     550000.0
97927     200000.0
97928     336000.0
Name: Maximum_salary, Length: 97929, dtype: float64
--------------------------------------------------
mussing value: 0
--------------------------------------------------
astype: 0         400000
1         500000
2         550000
3         200000
4        1800000
          ...
97924     200000
97925     550000
97926     550000
97927     200000
97928     336000
Name: Maximum_salary, Length: 97929, dtype: int64

In [83]:
# check Minimumexperience columns
# check data type
print("data type:",df['Minimumexperience'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Minimumexperience'].isna().sum())
print("-"*50)

# fill missing value using median
df['Minimumexperience']=df['Minimumexperience'].fillna(df['Minimumexperience'].median())
print(df['Minimumexperience'])

data type: float64
--------------------------------------------------
missing value: 571
--------------------------------------------------
0         2.0
1         6.0
2        12.0
3         0.0
4         5.0
         ...
97924     2.0
97925     1.0
97926     4.0
97927     0.0
97928     0.0
Name: Minimumexperience, Length: 97929, dtype: float64

In [84]:
print("missing value:",df['Minimumexperience'].isna().sum())
print("-"*50)

missing value: 0
--------------------------------------------------

In [85]:
# rename columns name
df = df.rename(columns={"Minimumexperience": "Minimum_experience"})
df.head(2)

,Title,Jobid,Currency,Jobuploaded,Companyname,Tagsandskills,Experience,Salary,Location,Companyid,Reviewscount,Aggregaterating,Jobdescription,Minimum_salary,Maximum_salary,Minimum_experience,Maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,0.0,3.7,Preferred Candidate Profile . .,200000,400000,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure Active Fire Protection System,Such As F...",300000,500000,6.0,11.0

In [86]:
# check Maximumexperience columns
# rename columns
df=df.rename(columns={"Maximumexperience":"Maximum_experience"})
df
# check missing value
print("missing value:",df['Maximum_experience'].isna().sum())
print("-"*50)

missing value: 571
--------------------------------------------------

In [87]:
# fill missing value using meadian
df['Maximum_experience']=df['Maximum_experience'].fillna(df['Maximum_experience'].median())
print("missing value:",df['Maximum_experience'])

missing value: 0         4.0
1        11.0
2        18.0
3         3.0
4        10.0
         ...
97924     5.0
97925     2.0
97926     9.0
97927     3.0
97928     3.0
Name: Maximum_experience, Length: 97929, dtype: float64

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               97929 non-null  object
 1   Jobid               97929 non-null  int64
 2   Currency            97929 non-null  object
 3   Jobuploaded         97929 non-null  object
 4   Companyname         97929 non-null  object
 5   Tagsandskills       97929 non-null  object
 6   Experience          97929 non-null  object
 7   Salary              97929 non-null  object
 8   Location            97929 non-null  object
 9   Companyid           97929 non-null  int64
 10  Reviewscount        97929 non-null  float64
 11  Aggregaterating     97929 non-null  float64
 12  Jobdescription      97929 non-null  object
 13  Minimum_salary      97929 non-null  int64
 14  Maximum_salary      97929 non-null  int64
 15  Minimum_experience  97929 non-null  float64
 16  Maximum_experience  97929 non-null  float64
dtypes: float64(4), int64(4), object(9)
memory usage: 12.7+ MB

In [89]:
# save data set
df.to_csv('indian_job_market_clean_data.csv', index=False)